name             'opennebula_ng'
maintainer       'Chris Aumann'
maintainer_email 'me@chr4.org'
license          'GNU Public License 3.0'
description      'Installs/Configures opennebula_ng'
long_description 'Installs/Configures opennebula_ng'
version          '5.1.0'
supports         'debian'
supports         'ubuntu'
depends          'apt'
depends          'nfs'
depends          'mysqld'
